add solution skeleton
js-tasks-ru/htmlcss-20230411_oksana-garibova pull request #11
Opened 2023-04-27 10:53 UTC by oksana-garibova

2023-04-27 10:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-28 14:43 UTC, GSemikozov requested changes

2023-04-28 14:43 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width:172px
ширину лучше в процентах

2023-05-01 11:48 UTC, GSemikozov approved these changes

2023-05-01 11:48 UTC, merged