add button
js-tasks-ru/htmlcss-20230411_oksana-garibova pull request #9
Opened 2023-04-24 11:10 UTC by oksana-garibova

2023-04-24 11:10 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-24 20:02 UTC, GSemikozov requested changes

2023-04-24 20:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    max-width:189px;
наоборот - min-width

2023-04-24 20:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding:15px;
`15px 15px 14px`

2023-04-24 20:02 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +.button_primary:disabled, .button_secondary:disabled, .button_alternate:disabled{
можно проще: `.button:primary`

2023-04-25 08:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-04-25 08:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-04-25 12:27 UTC, GSemikozov approved these changes

2023-04-25 12:27 UTC, merged